name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # Or 'main', depending on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # New auth action
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker with Google Container Registry
      run: |
        echo "${{ secrets.GCP_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/weathertrack:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/weathertrack:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy weathertrack \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/weathertrack:$GITHUB_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
